volume_name         = "volumename"
region              = "region"
protocol            = ["NFS or SMB"]
size                = 1024      #change this to what is needed
service_level       = "premium" #change to desired service level
network             = "vpc network"
storage_class       = "hardware or software"
zone                = "zone"
gcp_project         = "gcp project id"
gcp_service_account = "gcpkey.json"
